# Generated by Django 2.1.3 on 2019-01-18 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pointsheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('pointsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsheets.Pointsheet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='launche',
            unique_together={('date', 'time', 'pointsheet')},
        ),
    ]
