# Generated by Django 2.1.3 on 2019-01-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointsheets', '0002_auto_20190118_2244'),
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Launche',
            new_name='Launch',
        ),
    ]
